name: SkeetCliRelease
on:
  workflow_run:
    workflows: ["SkeetCliBuild"]
    types: [completed]
  push:
    branches:
      - main
    paths:
      - "packages/cli/**"
      - ".github/workflows/skeet-cli-release.yml"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  issues: write
  pull-requests: write
  packages: write

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: "20.11.0"
          cache: "pnpm"

      - name: install dependencies
        run: pnpm install

      - name: create and publish versions
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm ci:version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm -F cli ci:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send a Discord notification if a publish happens
        if: steps.changesets.outputs.published == 'true'
        # You can do something when a publish happens.
        run: discord:send --message "A new version of ${GITHUB_REPOSITORY} was published!"
